### ISSUE TITLE
Quiz Form

### ISSUE THREAD

**Issue by mavarreteno** [epicasino/Feed-Me#5]
Create the form for users to select the criteria that users want their selections to meet

**Comment by epicasino** [comment]
- [x] Create description of application in question-box element (According to wireframe)
- [x] When button is clicked to start, first question shows up on question-box, along with the 4 options
- [x] Rinse & repeat for all questions, then last question leads to result recipes

In JS- 
- [x] replace textcontent of question-box to the different questions, along with option-boxes to different options
- [x] create conditionals depending on which option-box was clicked according to question
- [x] button clicked would fill in variable object of 'query' with option content
- [x] when quiz is 'submitted' then the edamam api function is called with filled parameters from variable objects

**Comment by acolao** [comment]
Dietary Preferences:
HEALTH
1.	Vegan
2.	Keto-Friendly
3.	Vegetarian
4.	Gluten-Free
5.	No Restriction
Allergies
HEALTH
1.	Peanut-Free
2.	Dairy Free
3.	Shellfish-Free
4.	Tree-Nut-Free
5.	Wheat-Free
Meal Type
mealType
1.	breakfast
2.	brunch
3.	lunch/dinner
4.	snack
dishType
5.	desserts
Cuisine Type
cuisineType
1.	american
2.	asian
3.	mexican
4.	italian
5.	central europe
Diet
Diet
1.	High-Fiber
2.	High-Protein
3.	Low-Sodium
4.	Low-carb
5.	Low-fat
Calories
1.	100-500
2.	600-900
3.	1000-1500
4.	2000-2500
5.	2500+
