### ISSUE TITLE
UI

### ISSUE THREAD

**Issue by callmechelsea** [epicasino/Feed-Me#6]
- [x] make it pretty

**Comment by epicasino** [comment]
- [x] Have an established color-scheme
- [x] A nice font from Google Fonts
- [x] Polished navbar w/ updated logo (or keep current favicon)
- [ ] JS/CSS Animations for fading in/fading out questions/options
- [x] Work with API branch for appending information from API to the page (recipes, directions, etc)

**Comment by epicasino** [comment]
for recipe results cards 

- [x] hide option boxes for recipe cards
- [x] recipe cards w/ parsed data from edamam API fetch result
- [x] Two options:
- On recipe click, redirect to recipe link (window.location)
- On recipe click, open a modal w/ recipe ingredients and an <a> tag that leads to recipe link
